### ISSUE TITLE
Samrt Contracts Updates 

### ISSUE THREAD

**Issue by Guzbyte-tech** [Green-Cycle-Plus/Smart-Contract-V1#12]
**The waste management contract requires the various fixes.**

1. Get user requests: Create a function to be able to list all user requests. (Pending , finalized, etc)
2. Change recycler mapping of address to ID to recycler struct.
3. Add checks for collectors during address check on login. 
4. Change typo from recyclerOffer to recyclerOffers
5. Change  the array of recycler addresses to an array of structs of recyclers.
6. Renaming of recyclerCoordinate to recyclerCoordinates 
7.  Emit event on the contracts

8. Escrow final reward splitting (Percentage to user, platform)
9. Fetch all requests assigned to a particular collector.
10. Fetch all collectors of a particular recycler returns an array of Collector structs.

**Comment by kingAkande** [comment]
you mean  getting detailed information of all collectors for a particular recycler, as stated in 11

**Comment by Guzbyte-tech** [comment]
> you mean getting detailed information of all collectors for a particular recycler, as stated in 11

yes

**Comment by michojekunle** [comment]
@Guzbyte-tech I've reviewed and updated the issue details
